# Basic configuration for setting up the 

[global]
project = "twoDValidations"
project_name = "Signal processing" # toadd
file = "/Users/msotgia/dev_areas/twoDValidationsStudies/trackValidations/writerTwoDValidations.root"
# file = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/trackValidations/writerTwoDValidations.root"
# outdir = "/exp/icarus/app/users/msotgia/analysis/twoDRecoStudies/trackValidations/plotStuff/samplePlots/configurationSingles1D/"
outdir = "/Users/msotgia/dev_areas/twoDValidationsStudies/trackValidations/plotStuff/samplePlots/configurationSingles1D/"


[analysis_Muons]
merge_on = "Evt"
density = true

[[analysis_Muons.dataset]]
name = "Muons/DconfigA/configA"
# No `style` entr --> default to black line 2 pt
label = "1D signal proc."


[[analysis_Muons.dataset]]
name = "Muons/DconfigB/configB"
style = "style_2d"
label = "2D signal proc."

[[analysis_Muons.dataset]]
name = "Muons/DconfigC/configC"
# No `style` entr --> default to black line 2 pt
label = "2D + DNNROI w/o Pulse Trains"
style = "style_dnn"


[[analysis_Muons.dataset]]
name = "Muons/DconfigD/configD"
# No `style` entr --> default to black line 2 pt
label = "2D + DNNROI w/ Pulse Trains = 10"
style = "style_dnnpt"


[[analysis_Muons.plot]]
label = "Hit completeness"
product = "completeness"
yscale = "log"
binning = {bins = 50, limits = [0, 1], flow = false}

# [[analysis_Muons.plot]]
# label = ["Hit purity", "Hi completeness"]
# product = ["purity", "completeness"]
# binning = [{bins = 50, limits = [0, 1], flow = false}, {bins = 50, limits = [0, 1], flow = false}]


# [[analysis_Muons.plot]]


# Styles are passed to mplhep instances of `histplot`
[style_2d]
histtype = "fill"
# yerr = false
color = "crimson"
alpha = 0.5

[style_dnn]
histtype = "step"
color = "red"
yerr = false
linestyle = ":"
linewidth = 4

[style_dnnpt]
histtype = "step"
color = "darkred"
yerr = false
linestyle = "--"
linewidth = 2

# this overwrites the default style if needed
# [style_default]